"""Get Stable Periods Count — https://www.fastprep.io/problems/amazon-get-stable-periods-count

Write-up & approaches: ../../../docs/problems/amazon_oa/amazon-get-stable-periods-count.md

A team of financial analysts at Amazon closely monitors revenue generated by a newly launched product. They classify a period of one or more consecutive days as a stable-growth period if the revenue g

  uv run python amazon_oa/amazon-get-stable-periods-count/solution.py   # debug one case (see CASE below)
  uv run pytest amazon_oa/amazon-get-stable-periods-count/              # run the test sets
"""

from harness import NotSolved, pick_case


class Solution:
    def getStablePeriodsCount(self, revenues, k):
        """State the time and space complexity of your approach, and explain why.

        Time:  O(?):
        Space: O(?):
        """
        raise NotSolved


if __name__ == "__main__":
    # Debug playground: set a breakpoint in getStablePeriodsCount above, then run this file.
    # Pick a case by id (ids are in cases.json).
    CASE = "example_1"
    case = pick_case(__file__, CASE)
    result = Solution().getStablePeriodsCount(*case["args"])
    print(f"case {case['id']}: args = {case['args']}")
    print(f"expected: {case['expected']}")
    print(f"got:      {result}")
